# fly.toml app configuration file generated for yokaimedals-bot on 2025-08-26T20:17:30+02:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "yokaimedals-bot"
primary_region = "fra"

[env]
  # variabili d'ambiente che il bot leggerà con os.getenv (il bot token e' un secret)
  DB_PATH = "/dati_persistenti/database.db"
  LOG_PATH = "/dati_persistenti/admin_actions.log"
  YOKAI_JSON_PATH = "/dati_persistenti/yokai_list.json"
  
  # il punto d'innanzi ai path vuol dire che si parte dalla cartella /app/ di fly io, ossia la root dove sta main.py
  # Sono uguali al .env locale
  CONFIG_BOT_PATH = "./config/bot.yml"
  CONFIG_TEXTS_PATH = "./config/texts.yml"
  CONFIG_URLS_PATH = "./config/urls.yml"
  CONFIG_ADMINS_PATH = "./config/admins.yml"

  RESOURCES_OTHER_IMAGES_PATH = "./resources/other_images/"
  RESOURCES_YOKAI_IMAGES_PATH = "./resources/yokai_images/"


[mounts]
source = "dati_persistenti"
destination = "/dati_persistenti"


[[vm]]
size = "shared-cpu-1x"
memory = "256mb"

  