# fly.toml app configuration file generated for yokaimedals-bot on 2025-08-26T20:17:30+02:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "yokaimedals-bot"
primary_region = "fra"

[env]
  # variabili d'ambiente che il bot leggerà con os.getenv (il bot token e' un secret)
  DB_PATH = "/data/database.db"
  LOG_PATH = "/data/admin_actions.log"
  YOKAI_JSON_PATH = "/data/yokai_list.json"

[mounts]
source = "dati_persistenti"
destination = "/data"

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"

  