# fly.toml app configuration file generated for yokaimedals-bot on 2025-08-26T20:17:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yokaimedals-bot"
primary_region = "fra"

[mounts]
source = "database"
destination = "/data"

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"

  